# Generated by Django 5.0.4 on 2024-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekhoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='bot_message',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='message',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
