# Generated by Django 5.0.4 on 2024-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekhoapp', '0002_remove_chatconversation_bot_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='message',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='bot_message',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_message',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
