# Generated by Django 5.0.4 on 2024-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekhoapp', '0003_remove_chatconversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
